name: Deploy to Wikipedia (main branch)

on:
  # Run on every push (merge) to the main branch
  push:
    branches: [ main ]
  # Allow manual trigger
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install 'pywikibot>=9.0.0'

      - name: Deploy to MediaWiki:Form-assistant.js (production)
        env:
          BOT_NAME: ${{ secrets.BOT_NAME }}
          BOT_PASS: ${{ secrets.BOT_PASS }}
        run: |
          echo "('L235', BotPassword('${BOT_NAME}', '${BOT_PASS}'))" > user-password.py
          chmod 600 user-password.py

          python3 deploy.py \
            --file formAssistant.js \
            --branch main \
            --target "MediaWiki:Form-assistant.js" \
            --summary "Deploy revision [$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/commit/${GITHUB_SHA} ${GITHUB_SHA}]"